title: 飞鸟
# email: your-email@example.com
description: >- # 这意味着将下面的文本作为一个字符串，但是删除前导空格
  减熵生活
baseurl: "" # 如果你的网站在一个子路径下，例如example.com/blog，你应该设置这个值为"/blog"
url: "https://yzlun123.github.io" # 你的网站的主URL
# twitter_username: jekyllrb
# github_username:  jekyll
categories:
  - Category 1
  - Category 2
  - Category 3

header_pages:
  - index.md
  - category1.md
  - category2.md
  - category3.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed